# Generated by Django 4.1.7 on 2023-02-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='image',
            field=models.ImageField(upload_to='captchas'),
        ),
    ]
